export const SET_TODO_DATA = 'SET_TODO_DATA';

export const SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED';

export const GET_USER_INFO = 'GET_USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';
